name: Ejercicio_4

on:
  push:
    branches:
      - main
jobs:    
  
  Crear-aplicacion-php:
  
    runs-on: ubuntu-latest
  
    services:
      servidor_apache:
        image: httpd:latest
        ports:
           - 8080:80

    steps:
       
      - name: otorgar permisos
        run: sudo chmod -R 777 /var/www/html
       
      - name: ingresar carpeta html
        run: cd /var/www/html
        
      - name: crear archivo php
        run: sudo echo "<h3>Hola Mundo</3><p><?php echo 'Hora del sistema '.date('d-m-Y');?></p>" > inicio.php
        
      - name: ver archivo inicio.php
        run: sudo cat inicio.php
        
      - name: otorgar permisos
        run: sudo chmod -R 777 inicio.php

      - name: ver permisos
        run: ls -l
        
      - name: Acceder a la pagina
        run: sudo curl http://localhost:8080/inicio.php
